In [1]:
# Required Libraries

import yfinance as yf
import pandas as pd
import plotly.express as px

The main focus in this practice exercise is review and analyse last 5 year stock evolution for a company.

In my election I choosed Pfizer, I want to review how its value changed during all these years, because at current date (12/sept/2025) we're still so near of pandemic consequences.

In [2]:
# Extracting company
pfizer = yf.Ticker("PFE")

# Extracting company's real data
data = pfizer.history(period="5y").reset_index()

In [3]:
# All required data are available in "data" variable
# seeing a sample and reviewing data
data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2020-11-11 00:00:00-05:00,28.904107,29.885417,28.175558,28.621609,58980997,0.0,0.000
1,2020-11-12 00:00:00-05:00,28.458053,28.502659,27.684898,27.915358,46767877,0.0,0.000
2,2020-11-13 00:00:00-05:00,28.153248,28.740550,28.034302,28.710812,40175634,0.0,0.000
3,2020-11-16 00:00:00-05:00,28.145812,28.212719,27.394958,27.751801,75530167,0.0,0.000
4,2020-11-17 00:00:00-05:00,28.592203,28.600037,28.067214,28.239599,46984500,0.0,1.054

As extra step, we can made a data exploration to see little patterns and behaviors about the data

info() retrieve us descriptions about data types and data consistency while describe() will show us descriptive statistics about continuous variables data distribution

In [4]:
# Reviewing data info and description
print('Info data:')
print(data.info())

print('Data description:')
print(data.describe())

Info data:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1255 entries, 0 to 1254
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          1255 non-null   datetime64[ns, America/New_York]
 1   Open          1255 non-null   float64
 2   High          1255 non-null   float64
 3   Low           1255 non-null   float64
 4   Close         1255 non-null   float64
 5   Volume        1255 non-null   int64
 6   Dividends     1255 non-null   float64
 7   Stock Splits  1255 non-null   float64
dtypes: datetime64[ns, America/New_York](1), float64(6), int64(1)
memory usage: 78.6 KB
None
Data description:
              Open         High          Low        Close        Volume  \
count  1255.000000  1255.000000  1255.000000  1255.000000  1.255000e+03
mean     31.349942    31.686791    31.011323    31.346863  3.489909e+07
std       6.995465     7.115859     6.890208     7.016638  2.158399e+07
min      20.011080    20.854747    19.830970    20.466089  6.760200e+06
25%      24.999146    25.291128    24.752059    24.985152  2.224680e+07
50%      29.513153    29.642172    29.132858    29.433956  3.017210e+07
75%      37.242897    37.495115    36.824016    37.151571  4.048320e+07
max      49.341817    50.245604    48.714870    49.871059  3.499965e+08

         Dividends  Stock Splits
count  1255.000000   1255.000000
mean      0.006534      0.000840
std       0.051395      0.029752
min       0.000000      0.000000
25%       0.000000      0.000000
50%       0.000000      0.000000
75%       0.000000      0.000000
max       0.430000      1.054000

In [5]:
# To keep a clean format, we'll change the date format
data["Date"] = data["Date"].dt.tz_localize(None)
data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2020-11-11,28.904107,29.885417,28.175558,28.621609,58980997,0.0,0.000
1,2020-11-12,28.458053,28.502659,27.684898,27.915358,46767877,0.0,0.000
2,2020-11-13,28.153248,28.740550,28.034302,28.710812,40175634,0.0,0.000
3,2020-11-16,28.145812,28.212719,27.394958,27.751801,75530167,0.0,0.000
4,2020-11-17,28.592203,28.600037,28.067214,28.239599,46984500,0.0,1.054

Now once the data is saving, we can work with it, in this case, just we'll made a simple graph about daily price evolution

In [6]:
# Restructuring data to see both conditions (open price and clos price) by different subplots
df_long = data.melt(id_vars="Date", value_vars=["Open", "Close"],
                    var_name="Type", value_name="Price")

fig = px.line(
    data_frame = df_long,
    x = 'Date',
    y = 'Price',
    color = 'Type',
    facet_row = 'Type',
    title = 'PFE stock prices in the last 5 years'
)

# Render the image
fig.show()

As extra element, we want to include references based on State of Emergency caused by the COVID.

By the current case, we assume start date as 2020-03-15 and end date as 2021-07-01

In [7]:
# Define references Dates
start_date = pd.to_datetime("2020-03-15")
end_date   = pd.to_datetime("2021-07-01")

# Clear shapes over the graphs if necessary
fig.layout.shapes = ()
fig.layout.annotations = ()


# Adding vertical line references over the layout

# Line for start date
fig.add_shape(
    type="line",
    x0 = start_date,
    x1 = start_date,
    y0 = 0,
    y1 = 1,
    xref = "x",
    yref = "paper",
    line = dict(color="orange", width=2, dash="dash")
)
# Add a title for the start date reference line
fig.add_annotation(
    x = start_date,
    y = 1,
    xref = "x",
    yref = "paper",
    text = "Emergency Started",
    showarrow = False,
    yanchor = "bottom",
    font = dict(color="Orange")
)

# Line for end date
fig.add_shape(
    type = "line",
    x0 = end_date,
    x1 = end_date,
    y0 = 0,
    y1 = 1,
    xref = "x",
    yref = "paper",
    line = dict(color = "green", width = 2, dash = "dash")
)
# Add a title for the end date reference line
fig.add_annotation(
    x = end_date,
    y = 1,
    xref = "x",
    yref = "paper",
    text = "Emergency Ended",
    showarrow = False,
    yanchor = "bottom",
    font = dict(color="green")
)

fig.show()